version: '3'

# Services
# ------------------------------------------------------------
services:

  # MySQL
  # -----------------------------------------
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./config/mysql/my.cnf:/etc/my.cnf
      - ./data/db:/var/lib/mysql:delegated
      # - ./config/mysql/initial.sql:/docker-entrypoint-initdb.d/initial.sql

  # WordPress
  # -----------------------------------------
  wordpress:
    image: wordpress:5-fpm-alpine
    depends_on:
      - mysql
    ports:
      - 9000:9000
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
      WORDPRESS_TABLE_PREFIX: 'wp_'
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
    volumes:
      - ./data/wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/${THEME_NAME}
      - ./config/wordpress/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/wordpress/wpmp-config.php:/var/www/html/wp-content/wpmp-config.php

  # WP-CLI
  # -----------------------------------------
  wp-cli:
    build:
      context: ./config/wp-cli
    depends_on:
      - mysql
      - wordpress
    env_file:
      - .env
    volumes:
      - ./bin:/opt/bin
      - ./data/wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/${THEME_NAME}
    command: >
      /bin/sh -c '
        chmod u+x /opt/bin/*.sh \
        && /opt/bin/wait-for-it.sh mysql:3306 -t 60 -- /opt/bin/setup.sh
      '

  # Composer
  # -----------------------------------------
  composer:
    build:
      context: ./config/composer
    volumes:
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./data/wordpress:/app
    command: install

  # Nginx
  # -----------------------------------------
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./config/certs:/etc/nginx/certs
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ./data/wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/${THEME_NAME}

  # MailHog
  # -----------------------------------------
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  # Adminer
  # -----------------------------------------
  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: nette
